-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SETAPP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SETAPP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SETAPP` DEFAULT CHARACTER SET utf8 ;
USE `SETAPP` ;

-- -----------------------------------------------------
-- Table `SETAPP`.`PERFIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`PERFIL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PERFIL` VARCHAR(50) NOT NULL,
  `DESCRICAO` TEXT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `PERFIL_UNIQUE` (`PERFIL` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `USUARIO` VARCHAR(50) NOT NULL,
  `SENHA` VARCHAR(50) NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SITUACAO` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
  `PERFIL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USUARIO_UNIQUE` (`USUARIO` ASC) VISIBLE,
  INDEX `fk_USUARIO_PERFIL1_idx` (`PERFIL_ID` ASC) VISIBLE,
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_PERFIL1`
    FOREIGN KEY (`PERFIL_ID`)
    REFERENCES `SETAPP`.`PERFIL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`UNIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`UNIDADE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `BLOCO` VARCHAR(1) NOT NULL,
  `NUMERO` INT NOT NULL,
  `SITUACAO` ENUM('VAGO', 'OCUPADO') NOT NULL DEFAULT 'VAGO',
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_UNIDADE_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_UNIDADE_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`VISITANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`VISITANTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `SITUACAO` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
  `UNIDADE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_VISITANTE_UNIDADE1_idx` (`UNIDADE_ID` ASC) VISIBLE,
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_VISITANTE_UNIDADE1`
    FOREIGN KEY (`UNIDADE_ID`)
    REFERENCES `SETAPP`.`UNIDADE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`VEICULO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `SITUACAO` ENUM('ATIVA', 'INATIVA') NOT NULL,
  `UNIDADE_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_VEICULO_UNIDADE_idx` (`UNIDADE_ID` ASC) VISIBLE,
  INDEX `fk_VEICULO_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULO_UNIDADE`
    FOREIGN KEY (`UNIDADE_ID`)
    REFERENCES `SETAPP`.`UNIDADE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`AREA_RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`AREA_RESERVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `AREA` VARCHAR(45) NOT NULL,
  `DESCRICAO` TEXT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`RESERVA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `DATA_HORA_INICIO` DATETIME NOT NULL,
  `DATA_HORA_FIM` DATETIME NOT NULL,
  `SITUACAO` ENUM('ATIVO', 'CANCELADO', 'ENCERRADO') NOT NULL DEFAULT 'ATIVO',
  `AREA_RESERVA_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESERVA_AreaReserva1_idx` (`AREA_RESERVA_ID` ASC) VISIBLE,
  INDEX `fk_RESERVA_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_AreaReserva1`
    FOREIGN KEY (`AREA_RESERVA_ID`)
    REFERENCES `SETAPP`.`AREA_RESERVA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`OCORRENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`OCORRENCIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `OCORRENCIA` VARCHAR(100) NOT NULL,
  `DESCRICAO` TEXT NOT NULL,
  `DATA_HORA_OCORRENCIA` DATETIME NOT NULL,
  `DATA_HORA_CONCLUSAO` DATETIME NULL,
  `SITUACAO` ENUM('PENDENTE', 'CONCLUIDO') NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_OCORRENCIA_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OCORRENCIA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`COMUNICADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`COMUNICADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `TITULO` VARCHAR(100) NOT NULL,
  `DESCRICAO` TEXT NOT NULL,
  `SITUACAO` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_COMUNICADO_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMUNICADO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`ASSEMBLEIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`ASSEMBLEIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `MOTIVO` VARCHAR(150) NOT NULL,
  `DATA_HORA_AGENDAMENTO` DATETIME NOT NULL,
  `DATA_HORA_CONCLUSAO` DATETIME NULL,
  `SITUACAO` ENUM('PENDENTE', 'CONCLUIDA') NOT NULL DEFAULT 'PENDENTE',
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ASSEMBLEIA_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ASSEMBLEIA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`CORRESPONDENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`CORRESPONDENCIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `DESCRICAO` TEXT NOT NULL,
  `DATA_HORA_RECEBIDA` DATETIME NOT NULL,
  `DATA_HORA_RETIRADA` DATETIME NULL,
  `SITUACAO` ENUM('PENDENTE', 'RETIRADA') NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CORRESPONDENCIA_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CORRESPONDENCIA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SETAPP`.`BOLETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SETAPP`.`BOLETO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA_CADASTRO` DATETIME NOT NULL,
  `ARQUIVO` TEXT NOT NULL,
  `SITUACAO` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_BOLETO_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_BOLETO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `SETAPP`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
