SET @@global.time_zone = '+3:00';

USE SETAPP;

INSERT INTO PERFIL
(PERFIL, DESCRICAO) 
VALUES
('SINDICO', 'PERMISSAO DE SINDICO'),
('ADMINISTRADORA', 'PERMISSAO DE ADMINISTRADORA'), 
('MORADOR', 'PERMISSAO DE MORADOR');

INSERT INTO USUARIO
(DATA_HORA_CADASTRO, USUARIO, SENHA, NOME, CPF, EMAIL, SITUACAO, PERFIL_ID) 
VALUES
(now(), 'adm', 'adm', 'Felipe Fragoso Carneiro', '04290621171', 'felipe.fragosoc@gmail.com', 'ATIVO', 1);

INSERT INTO UNIDADE
(DATA_HORA_CADASTRO, BLOCO, NUMERO, SITUACAO, USUARIO_ID)
VALUES
(now(), 'A', '101', 'OCUPADO', 1);

INSERT INTO VISITANTE
(DATA_HORA_CADASTRO, NOME, CPF, SITUACAO, UNIDADE_ID)
VALUES
(now(), 'Ana Luíza Ferreira', '00000000000', 'ATIVO', 1);